### ISSUE TITLE
Remove use of google account from website

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlehack20#38]
Currently the website uses our Google Cloud API to send messages to pub/subs, this is really risky... By running as a service account instead, and giving this service account the right credentials, we can avoid using having our account into in the repo

**Comment by n8kim1** [comment]
resolved by nonurgency

**Comment by n8kim1** [comment]
This seems pretty tough: the deployed website (on gcloud vm's) will be running using the service account, but the service account key is still needed on our machines in order for local testing to work. So this probably necessitates two versions of the code -- one for running as the service account and one not?
Also, methods

**Comment by j-mao** [comment]
I think it should be possible to have the key saved locally and gitignored:

- In prod, this will run fine without the key, since it's configured to be injected into the instance.
- In dev/testing, you can export the env variable `GOOGLE_APPLICATION_CREDENTIALS=path/to/key.json`, and things will run without any changes to code.

And yes the key is actually a json and not just a slab of text. So when you generate the key you can just save the json file somewhere locally and have it under gitignore.

**Comment by n8kim1** [comment]
Oh yeah paths would work, thanks!

Would also have to refactor code to  use the JSON file — as it really should’ve from the beginning

**Comment by n8kim1** [comment]
In production, would GOOGLE_APP_CREDENTIALS or smth become an env? Or is how it works more subtle than this?

**Comment by j-mao** [comment]
The console has an option to change the service account when you spin up an instance (see screenshot), so can configure it from there. I'm not sure exactly how it works internally, but I'm fairly sure it works without the key and some other way.

![Screen Shot 2020-06-08 at 12 42 19 pm](https://user-images.githubusercontent.com/16425187/83988060-7fe9e180-a985-11ea-8366-56f01e625993.png)
